import {JSDOM} from 'jsdom';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../admin.html',import.meta.url),'utf8');
const dom=new JSDOM('<main></main>',{runScripts:'outside-only'});
const w=dom.window;
w.eval(`const esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');${html.slice(html.indexOf('function tableColumnKind'),html.indexOf('function localDateISO'))}`);
const headers=['วันที่','พนักงาน','สถานะ','เข้า','ออก','OT','เหตุผล','จัดการ'];
w.document.querySelector('main').innerHTML=w.table(headers,['<tr><td>2026-10-09</td><td>DEMO01</td><td>WORKING</td><td>10:00</td><td>20:00</td><td>1:00</td><td>เหตุผล &lt;ไม่ใช่ HTML&gt;</td><td><button onclick="edit()">แก้</button></td></tr>']);
const detail=w.document.querySelector('.record-detail');
assert.equal(detail.hidden,false);assert.match(detail.textContent,/เหตุผล <ไม่ใช่ HTML>/);
assert.equal(w.document.querySelectorAll('[aria-controls], [hidden]').length,0);
assert.ok(w.document.querySelector('button[onclick="edit()"]'));assert.equal(w.document.querySelector('[data-label="OT"]').textContent,'1:00');
assert.equal(w.document.querySelectorAll('script').length,0);
const monthlyHeaders=['วันที่','สถานะ','Shift','Event ลงเวลาทั้งหมด','เข้า','ออก','เวลาทำงาน','เวลาที่ต้องทำ','พัก','เติมของ','ขาด','OT','สาขา','ปัญหา'];
const wide=w.wideTable(monthlyHeaders,['<tr>'+monthlyHeaders.map((h,i)=>`<td class="value-${i}">unique-value-${i}-end</td>`).join('')+'</tr>']);
w.document.querySelector('main').innerHTML=wide;
for(let i=0;i<monthlyHeaders.length;i++)assert.ok(w.document.body.textContent.includes(`unique-value-${i}-end`));
assert.equal(w.document.querySelectorAll('th').length,5);
assert.equal(w.document.querySelectorAll('[hidden], [aria-controls]').length,0);
assert.ok(w.document.querySelector('.value-6'));
assert.ok(!html.includes('id="sendMiddayReport"')&&!html.includes('id="sendEnddayReport"'));
dom.window.close();console.log('PASS compact records retain all data/actions, escape text, show every field immediately, including all monthly fields');
