import {JSDOM} from 'jsdom';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../admin.html',import.meta.url),'utf8');
const dom=new JSDOM('<main></main>',{runScripts:'outside-only'}),w=dom.window;
w.eval(html.slice(html.indexOf('function tableColumnKind'),html.indexOf('function localDateISO')));
const headers=['วันที่','สถานะ','Shift','Event ลงเวลาทั้งหมด','เข้า','ออก','เวลาทำงาน','เวลาที่ต้องทำ','พัก','เติมของ','ขาด','OT','สาขา','ปัญหา'];
w.document.querySelector('main').innerHTML=w.table(headers,['<tr>'+headers.map((h,i)=>`<td class="value-${i}">value-${i}</td>`).join('')+'</tr>']);
assert.equal(w.document.querySelectorAll('thead th').length,14);
assert.equal(w.document.querySelectorAll('tbody tr').length,1);
assert.equal(w.document.querySelectorAll('tbody td').length,14);
assert.equal(w.document.querySelectorAll('[hidden], [aria-controls]').length,0);
assert.ok(w.document.querySelector('.value-11'));
assert.equal(w.document.querySelectorAll('td[data-column=events]').length,1);
assert.ok(!html.includes('id="sendMiddayReport"')&&!html.includes('id="sendEnddayReport"'));
dom.window.close();console.log('PASS traditional report keeps all 14 columns in one row, visible values and no send buttons');
