// Isolated UI fixture server. Never contacts production or persists HR data.
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const employee={id:'fixture-employee',employee_code:'DEMO01',display_name:'พนักงานตัวอย่าง ชื่อภาษาไทยยาวสำหรับทดสอบ',ba_mode:'FIXED_BRANCH',active:true,line_user_id:'fixture-line',default_shift_id:'demo-shift',offices:{office_name:'สาขาตัวอย่าง'},supervisors:{supervisor_name:'หัวหน้างานตัวอย่าง'}};
const data={employees:[employee,{...employee,id:'inactive',employee_code:'DEMO02',active:false}],supervisors:[],offices:[{id:'office',office_name:'สาขาตัวอย่าง',active:true}],shifts:[{id:'demo-shift',shift_name:'กะ 11:00',start_time:'11:00',end_time:'20:00'}],leaves:[],attendance:[],schedules:[],daily:[],monthly:[],registrations:[],line_logs:[],audits:[]};
const home={state:{label:'IN',office_name:'สาขาตัวอย่าง'},shift:{name:'กะ 11:00',start_time:'11:00',end_time:'20:00'},summary:{first_in:'10:55',credited_minutes:300,live_work_minutes:300,break_minutes:0,over_minutes:0,short_minutes:0,is_working:true},timeline:[{type:'IN',time:'10:55'}],allowed_actions:['BREAK_OUT']};
const req={id:'demo-request',employees:employee,request_date:'2026-10-09',request_side:'BREAK_OUT',office_id:'office',status:'PENDING',reason:'ลืมระบุเวลาขณะส่งคำขอ ขอให้หัวหน้างานตรวจสอบก่อนดำเนินการ',created_at:'2026-10-09T06:00:00Z'};
const context={request:req,employee,date:'2026-10-09',offices:data.offices,events:[{id:'in-event',event_type:'IN',occurred_at:'2026-10-09T03:55:00Z',office_id:'office'}],history_version:'fixture-only'};
const fixture=`window.BA_API={request:async(action,payload)=>{const data=${JSON.stringify(data)},home=${JSON.stringify(home)},request=${JSON.stringify(req)},context=${JSON.stringify(context)};if(action==='employee_home')return home;if(action==='supervisor_dashboard_v2')return {kpis:{total:2,checked_in:1,checked_out:0,working:1,on_break:0,late:0,leave:1,incomplete:0,pending_attendance:1},lists:{}};if(action==='pending_gps_requests')return {rows:[]};if(action==='employee_shift_month')return {rows:Array.from({length:31},(_,i)=>({date:'2026-10-'+String(i+1).padStart(2,'0'),status:i%7===0?'OFF':'WORK',shift_name:'กะ 11:00',start_time:'11:00',end_time:'20:00'}))};if(action==='employee_history_detail')return {rows:[{work_date:'2026-10-09',shift_name:'กะ 11:00',events:[{time:'10:55',label:'เข้างาน',office_name:'สาขาตัวอย่าง'}]}]};if(action==='attendance_review_context')return context;if(action==='review_attendance_request')return {success:true};if(action==='pending_attendance_correction_requests')return {rows:[request]};if(action==='shift_request_setup')return {shifts:data.shifts,offices:data.offices,attendance_requests:[request],requests:[]};if(action==='my_leave_history')return {rows:[]};throw Error('Fixture action: '+action);}};`;
http.createServer((request,response)=>{const url=new URL(request.url,'http://localhost');let route=url.pathname==='/'?'/index.html':url.pathname;const file=path.resolve(root,'.'+route);if(!file.startsWith(root+path.sep)){response.writeHead(403);return response.end();}try{let body=fs.readFileSync(file);if(route.endsWith('.html')){body=body.toString().replace(/<script src="https:[^>]*><\/script>/g,'').replace(/<script src="(?:config|api|admin-config)\.js[^>]*><\/script>/g,'');if(route==='/index.html')body=body.replace("window.addEventListener('load',init)",`window.addEventListener('load',()=>{${fixture}$('loading').classList.add('hidden');$('portal').classList.remove('hidden');$('name').textContent=${JSON.stringify(employee.display_name)};$('role').textContent='BA · ข้อมูลทดสอบ';$('version').textContent='v4.7.0';${url.searchParams.get('view')==='supervisor'?'renderSupervisorHome()':'renderEmployeeHome()'};})`);else if(route==='/admin.html')body=body.replace(/window.addEventListener\('load',\(\)=>\{const k=localStorage[\s\S]*?\}\);/,`window.addEventListener('load',()=>{DATA=${JSON.stringify(data)};api=async(action)=>action==='attendance_requests'?{corrections:[${JSON.stringify(req)}],gps:[]}:action==='attendance_review_context'?${JSON.stringify(context)}:{data:DATA};$('loginBox').classList.add('hidden');$('app').classList.remove('hidden');buildTabs();render();});`);}
response.setHeader('Content-Type',route.endsWith('.css')?'text/css':route.endsWith('.js')?'application/javascript':route.endsWith('.ttf')?'font/ttf':'text/html; charset=utf-8');response.end(body);}catch{response.writeHead(404);response.end('Not found');}}).listen(4177,'127.0.0.1',()=>console.log('UI fixtures http://127.0.0.1:4177'));
