import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {stripTypeScriptTypes} from 'node:module';
const html=fs.readFileSync(new URL('../admin.html',import.meta.url),'utf8');
const pending=[],els={monthlyMonth:{value:'2026-09'},dailyDate:{value:'2026-10-08'}};
const c=vm.createContext({DATA:{},current:'monthly',monthlyMatrixLoading:false,$:id=>els[id],bangkokDateKey:()=> '2026-10-08',daysInMonth:()=>30,window:{},esc:x=>x,render:()=>{},msg:()=>{},api:(action,p)=>new Promise((resolve,reject)=>pending.push({action,p,resolve,reject}))});
vm.runInContext(html.slice(html.indexOf('let reportGeneration='),html.indexOf('function buildTabs()')),c);
const one=c.loadSummaryPeriod();els.monthlyMonth.value='2026-08';const two=c.loadSummaryPeriod();
const reply=(n)=>({complete:true,data:{daily:[{id:n}],schedules:[],leaves:[],attendance:[]}});
pending[1].resolve(reply('aug'));await two;pending[0].resolve(reply('sept'));await one;assert.equal(c.DATA.daily[0].id,'aug');assert.equal(c.reportGuard(),'');
const three=c.loadSummaryPeriod();pending[2].reject(Error('network'));await three;assert.match(c.reportGuard(),/network/);assert.equal(c.window.__currentSummaryRows.length,0);
console.log('PASS overlapping month loads ignore stale response; failed reports cannot be exported');
const api=fs.readFileSync(new URL('../supabase/functions/admin-api/index.ts',import.meta.url),'utf8');
const block=api.slice(api.indexOf("    if(action==='report_data')"),api.indexOf("    if(action==='list_attendance')"));
const counts={daily_summaries:1501,employee_schedules:2000,leave_requests:3,attendance_events:12001};
let fail=false;const db={from(table){let from,to;const q={select(){return q},gte(){return q},lte(){return q},order(){return q},is(){return q},range(a,b){from=a;to=b;return q},then(resolve){resolve(fail?{error:Error('db failure')}:{data:Array.from({length:Math.max(0,Math.min(to+1,counts[table])-from)},(_,i)=>({id:from+i}))})}};return q}};
const ac=vm.createContext({sb:db,json:x=>x,fail:message=>({error:message})});
vm.runInContext(stripTypeScriptTypes(`async function run(p){const action='report_data';${block}}`),ac);
const r=await ac.run({start_date:'2026-09-01',end_date:'2026-09-30'});assert.equal(r.complete,true);assert.equal(r.data.daily.length,1501);assert.equal(r.data.schedules.length,2000);assert.equal(r.data.attendance.length,12001);assert.equal(r.data.attendance.at(-1).id,12000);
assert.ok((await ac.run({start_date:'2026-02-30',end_date:'2026-03-01'})).error);fail=true;await assert.rejects(ac.run({start_date:'2026-09-01',end_date:'2026-09-30'}),/db failure/);
console.log('PASS all report tables paginate beyond row ceilings, reject invalid dates and fail on partial data');
const ba=fs.readFileSync(new URL('../supabase/functions/ba-api/index.ts',import.meta.url),'utf8');
const recalc=ba.slice(ba.indexOf('async function recalc(employeeId:'),ba.indexOf('function fmtTimeTH'));
let writes=0;const failure=Error('RPC unavailable');const bc=vm.createContext({sb:{rpc:async()=>({error:failure}),from:()=>{writes++;throw Error('unexpected fallback write')}},sync:async()=>{}});
vm.runInContext(stripTypeScriptTypes(recalc),bc);await assert.rejects(bc.recalc('employee','2026-09-01'),/RPC unavailable/);assert.equal(writes,0);
console.log('PASS calculation failure cannot overwrite summaries with an alternative formula');
